### ISSUE TITLE
How to test configuration without needing to wait for new feed?

### ISSUE THREAD

**Issue by Iliannnn** [JakobST1n/RSS-watcher#5]
How to force a push message?

**Comment by JakobST1n** [comment]
Hi,
There is not really any built-in way to do this.
If the feed in question does have elements, you could set `last_fetch` to `0` to make it send notifications for all the elements currently in the feed; `UPDATE rss-watcher-feeds SET last_fetch = 0 WHERE id = <feed>`.

**Comment by Iliannnn** [comment]
> Hi, There is not really any built-in way to do this. If the feed in question does have elements, you could set `last_fetch` to `0` to make it send notifications for all the elements currently in the feed; `UPDATE rss-watcher-feeds SET last_fetch = 0 WHERE id = <feed>`.

I will try that, thanks!
